markdown  : maruku
permalink : pretty
pygments  : true
redirects : true
exclude   :
  - README.md

author      : Saigon Apps, @saigonapps
email       : saigonapps@gmail.com
url         : http://appsaigon.com
description : Saigon Apps making apps from Saigon.

# Custom variables.
analytics   : UA-55131285-2